# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Task9spec' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'task9spec' do
    @driver.get('http://localhost:3000/task9/input')
    @driver.find_element(:id, 'digit').click
    @driver.find_element(:id, 'digit').send_keys('3')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:id, 'result').text).to include('153')
  end
end
